title: Be Sweet Bakery
email: besweetomaha@gmail.com
phone: 1-402-658-8810
baseurl:
url: http://besweetomaha.com
facebook: https://www.facebook.com/besweetomaha
twitter: https://twitter.com/besweetomaha
description: Be Sweet Bakery in Omaha Nebraska serving custom cheesecakes, cupcakes, cookies, and much more.
keywords: be,sweet,bakery,omaha,nebraska,brianna,pigsley,parriott,cheesecakes,cupcakes,cookies,custom

markdown: kramdown

sass:
  style: compressed

menu:
  1:
    title: Jumbo Muffins
    images:
      - /assets/images/dist/muffins.jpg
    is_featured: false
    description: Poppy Seed with Lemon Glaze, Banana, Cappuccino Chocolate Chip, Blueberry Crumb, Double Chocolate Chip, Banana, Cinnamon Sugar, Almond, or request a custom flavor! – minimum of ½ doz. Per type required
  2:
    title: Cupcakes
    images:
      - /assets/images/dist/specialty_cupcakes.jpg
      - /assets/images/dist/cloud_cupcakes.jpg
      - /assets/images/dist/football_cupcakes.jpg
    is_featured: true
    description: Custom decorations available, prices for those may vary. Minimum order of one dozen per type. Cupcake pull apart cakes available.
  3:
    title: 9 Inch Cheesecake
    images:
      - /assets/images/dist/snickers_cheesecake.jpg
      - /assets/images/dist/espresso_cheesecake.jpg
    is_featured: true
    description: Peanut Butter Fudge, Snickers, Cappuccino Fudge, Red Velvet, Carrot Cake, Classic New York with Cherries or Strawberries, or request your own flavor
  4:
    title: Cupcake Sized Cheesecake
    images:
      - /assets/images/dist/strawberry_cupcakes.jpg
    is_featured: false
  5:
    title: Custom Cake
    images:
      - /assets/images/dist/flower_cake_1.jpg
      - /assets/images/dist/flower_cake_2.jpg
      - /assets/images/dist/gender_reveal_cake.jpg
      - /assets/images/dist/smash_cake.jpg
      - /assets/images/dist/pink_champagne_cake.jpg
      - /assets/images/dist/gun_target_cake.jpg
      - /assets/images/dist/doughnut_coffee_cake.jpeg
      - /assets/images/dist/cross_cake.jpeg
    is_featured: false
    description: Request your flavor, design, and size. Feel free to send an email and attach a photo of your design.
  6:
    title: Cinnamon Rolls
    images:
      - /assets/images/dist/default.jpg
    is_featured: false
    description: Cinnamon Rolls with Cream Cheese Frosting, Pecan Caramel Cinnamon Rolls, or Peanut Butter Cinnamon Rolls
  7:
    title: Custom Design Cookies
    images:
      - /assets/images/dist/made_with_love.jpg
      - /assets/images/dist/fall_cookies.jpg
      - /assets/images/dist/home_sweet_home.jpg
      - /assets/images/dist/halloween_cookies.jpg
    is_featured: true
    description: Can be individually wrapped
  8:
    title: Brownies & Bars
    images:
      - /assets/images/dist/brownies.jpg
      - /assets/images/dist/lemon_cream_crumb_bars.jpg
    is_featured: false
  9:
    title: Quiches and Pies
    images:
      - /assets/images/dist/quiche.jpg
      - /assets/images/dist/apple_pie.jpg
    is_featured: false
  10:
    title: Cupcake Bouquets
    images:
      - /assets/images/dist/cupcake_bouquet.jpg
    is_featured: false
  11:
    title: Cake Pops
    images:
      - /assets/images/dist/cake_pops.jpg
    is_featured: false
  