title: Be Sweet Bakery
email: besweetomaha@gmail.com
phone: 1-402-658-8810
baseurl:
url: http://besweetomaha.com
facebook: https://www.facebook.com/besweetomaha
twitter: https://twitter.com/besweetomaha
description: Be Sweet Bakery in Omaha Nebraska serving custom cheesecakes, cupcakes, cookies, and much more.
keywords: be,sweet,bakery,omaha,nebraska,brianna,pigsley,parriott,cheesecakes,cupcakes,cookies,custom

markdown: kramdown

sass:
  style: compressed

menu:
  1:
    title: Cupcakes
    price: Prices Vary
    images:
      - /assets/images/dist/specialty_cupcakes.jpg
      - /assets/images/dist/cloud_cupcakes.jpg
      - /assets/images/dist/football_cupcakes.jpg
    is_featured: true
    description: Regular size $1.50, mini $0.75, and jumbo $2.00 each. Custom decorations available, prices for those may vary. Minimum order of one dozen per type. Cupcake pull apart cakes available.
  2:
    title: 9 Inch Cheesecake
    price: Prices Vary
    images:
      - /assets/images/dist/snickers_cheesecake.jpg
      - /assets/images/dist/espresso_cheesecake.jpg
    is_featured: true
    description: Peanut Butter Fudge, Snickers, Cappuccino Fudge, Red Velvet, Carrot Cake, Classic New York with Cherries or Strawberries, or request your own flavor
  3:
    title: Cupcake Sized Cheesecake
    price: Prices Vary
    images:
      - /assets/images/dist/strawberry_cupcakes.jpg
    is_featured: false
  4:
    title: Custom Cake
    price: Prices Vary
    images:
      - /assets/images/dist/flower_cake_1.jpg
      - /assets/images/dist/flower_cake_2.jpg
      - /assets/images/dist/gender_reveal_cake.jpg
      - /assets/images/dist/smash_cake.jpg
      - /assets/images/dist/pink_champagne_cake.jpg
      - /assets/images/dist/gun_target_cake.jpg
      - /assets/images/dist/doughnut_coffee_cake.jpeg
      - /assets/images/dist/cross_cake.jpeg
    is_featured: false
    description: Request your flavor, design, and size. Feel free to send an email and attach a photo of your design.
  5:
    title: Custom Design Cookies
    price: $12.00/dozen
    images:
      - /assets/images/dist/made_with_love.jpg
      - /assets/images/dist/fall_cookies.jpg
      - /assets/images/dist/home_sweet_home.jpg
      - /assets/images/dist/halloween_cookies.jpg
    is_featured: true
    description: Can be individually wrapped
  6:
    title: Brownies & Bars
    price: Prices Vary
    images:
      - /assets/images/dist/brownies.jpg
      - /assets/images/dist/lemon_cream_crumb_bars.jpg
    is_featured: false
  7:
    title: Cake Pops
    price: Prices Vary
    images:
      - /assets/images/dist/cake_pops.jpg
    is_featured: false
  
