title: Be Sweet Bakery
email: besweetomaha@gmail.com
phone: 1-402-658-8810
baseurl:
url: http://besweetomaha.com
facebook: https://www.facebook.com/besweetomaha
twitter: https://twitter.com/besweetomaha
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Build settings
markdown: kramdown

sass:
  style: compressed

menu:
  1:
    title: Jumbo Muffins
    price: $2.00
    image: /assets/images/dist/muffins.jpg
    is_featured: false
  2:
    title: Cupcakes
    price: $2.00
    image: /assets/images/dist/football_cupcakes.JPG
    is_featured: true
  3:
    title: 9 Inch Cheesecake
    price: Prices Vary
    image: /assets/images/dist/cheesecake.JPG
    is_featured: true
  4:
    title: Cupcake Sized Cheesecake
    price: $2.50 (minimum 1 dozen)
    image: /assets/images/dist/default.jpg
    is_featured: false
  5:
    title: Custom Cake
    price: Prices Vary
    image: /assets/images/dist/flower_cake.jpg
    is_featured: false
  6:
    title: Cinnamon Rolls
    price: $18.00/dozen
    image: /assets/images/dist/default.jpg
    is_featured: false
  7:
    title: Custom Design Cookies
    price: $12.00/dozen
    image: /assets/images/dist/halloween_cookies.JPG
    is_featured: true
  8:
    title: Brownies & Bars
    price: $15.00/dozen
    image: /assets/images/dist/brownies.JPG
    is_featured: false
  9:
    title: Quiches and Pies
    price: $13.00
    image: /assets/images/dist/quiche.jpg
    is_featured: false
  10:
    title: Cupcake Bouquets
    price: $30.00
    image: /assets/images/dist/cupcake_bouquet.jpg
    is_featured: false
  11:
    title: Cake Pops
    price: $18.00/dozen
    image: /assets/images/dist/cake_pops.jpg
    is_featured: false
  12:
    title: Specialty Bread Loafs
    price: $8.00
    image: /assets/images/dist/default.jpg
    is_featured: false
  13:
    title: Coconut Macaroons
    price: $12.00/dozen
    image: /assets/images/dist/default.jpg
    is_featured: false
  